[package]
name = "octoscript-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Bounded, host-neutral Octoscript VM runtime"

[lints]
workspace = true

[dependencies]
octoscript-ui-l0 = { path = "../octoscript-ui-l0" }
makepad-script = { git = "https://github.com/OctoSense-org/makepad.git", rev = "3090964f9eba54c9384c0b55d2b4869c80305f7b" }
serde_json = "1.0.150"
